Repository theforeman/foreman_templates, pull requests merged in 2018-07, with the labels that each got.

#100 Update readme
  README.md
Labels: Needs testing, Not yet reviewed

#96 Fixes #23958 - Improve error message for file system access denial
  app/services/foreman_templates/action.rb
Labels: Needs testing

#97 Fixes #23894 - Fix import from git subdirectory
  app/services/foreman_templates/template_importer.rb
Labels: Needs testing, Not yet reviewed

#102 Fixes #24208 - Fix print output for rake task
  lib/tasks/foreman_templates_tasks.rake
Labels: Ready to merge

#103 Fix rubocop again
  .rubocop.yml
  Gemfile
  lib/tasks/foreman_templates_tasks.rake
Labels: Needs testing, Not yet reviewed
