Repository theforeman/foreman_templates, pull requests merged in 2018-05, with the labels that each got.

#90 Fixes #23420 - make dump dir locale independent
  app/services/foreman_templates/template_exporter.rb
  test/unit/template_exporter_test.rb
Labels: Ready to merge

#86 Fixes #22789 - Add structured data as a response
  .rubocop_todo.yml
  app/controllers/api/v2/template_controller.rb
  app/services/foreman_templates/action.rb
  app/services/foreman_templates/export_result.rb
  app/services/foreman_templates/parse_result.rb
  app/services/foreman_templates/template_exporter.rb
  app/services/foreman_templates/template_importer.rb
  lib/tasks/foreman_templates_tasks.rake
  test/unit/action_test.rb
  test/unit/template_importer_test.rb
Labels: Needs testing, Ready to merge

#91 Fixes #22787 - use app logger
  .rubocop.yml
  app/services/foreman_templates/parse_result.rb
  app/services/foreman_templates/template_exporter.rb
  app/services/foreman_templates/template_importer.rb
Labels: Needs testing, Not yet reviewed

#93 Use HTTPS in the gemspec website URL
  foreman_templates.gemspec
Labels: Needs testing, Not yet reviewed
