Repository theforeman/foreman_templates, pull requests merged in 2020-01, with the labels that each got.

#104 Foreman Templates Tier1 API tests automated
  .rubocop.yml
  test/functional/api/v2/template_controller_test.rb
  test/integration/foreman_templates_integration_test.rb
  test/templates/core/filter1.erb
  test/templates/with_prefix/filter1.erb
  test/templates/with_prefix/ptable1.erb
  test/templates/with_taxonomies/filter1.erb
  test/templates/with_taxonomies/metadata1.erb
  test/templates/with_taxonomies/metadata2.erb
  test/templates/with_taxonomies/ptable1.erb
  test/templates/with_taxonomies/snippet1.erb
  test/test_plugin_helper.rb
Labels: Needs testing, Not yet reviewed

#132 Fixes #28632 - Expose additional info in API
  app/services/foreman_templates/parse_result.rb
Labels: Needs testing

#136 Refs #28256 - upgrade tfm-builder to v4
  package.json
Labels: Needs testing

#137 Fixes #28750 - Template controller name must be plural
  app/controllers/api/v2/template_controller.rb
Labels: Needs re-review, Needs testing

#131 Fixes # 28492 - Use formik instead of redux-forms
  webpack/__mocks__/foremanReact/components/common/forms/ForemanForm.js
  webpack/__mocks__/foremanReact/components/common/forms/Form.js
  webpack/components/NewTemplateSync/__fixtures__/templateSyncSettings.fixtures.js
  webpack/components/NewTemplateSync/__tests__/__snapshots__/NewTemplateSync.test.js.snap
  webpack/components/NewTemplateSync/components/NewTemplateSyncForm/NewTemplateSyncForm.js
  webpack/components/NewTemplateSync/components/NewTemplateSyncForm/NewTemplateSyncFormConstants.js
  webpack/components/NewTemplateSync/components/NewTemplateSyncForm/NewTemplateSyncFormSelectors.js
  webpack/components/NewTemplateSync/components/NewTemplateSyncForm/__tests__/NewTemplateSyncForm.test.js
  webpack/components/NewTemplateSync/components/NewTemplateSyncForm/__tests__/NewTemplateSyncFormSelectors.test.js
  webpack/components/NewTemplateSync/components/NewTemplateSyncForm/__tests__/__snapshots__/NewTemplateSyncForm.test.js.snap
  webpack/components/NewTemplateSync/components/NewTemplateSyncForm/__tests__/__snapshots__/NewTemplateSyncFormSelectors.test.js.snap
  webpack/components/NewTemplateSync/components/NewTemplateSyncForm/index.js
  webpack/components/NewTemplateSync/components/SyncSettingField.js
  webpack/components/NewTemplateSync/components/SyncSettingFields.js
  webpack/components/NewTemplateSync/components/TextButtonField/index.js
  webpack/components/NewTemplateSync/components/__tests__/SyncSettingField.test.js
  webpack/components/NewTemplateSync/components/__tests__/SyncSettingFields.test.js
  webpack/components/NewTemplateSync/components/__tests__/TextButtonField.test.js
  webpack/components/NewTemplateSync/components/__tests__/__snapshots__/SyncSettingField.test.js.snap
  webpack/components/NewTemplateSync/components/__tests__/__snapshots__/SyncSettingFields.test.js.snap
  webpack/components/NewTemplateSync/components/__tests__/__snapshots__/TextButtonField.test.js.snap
Labels: Needs testing
